### find a particular user with given id
Get http://localhost:3000/auth/4

### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}
### signin in as an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

###Get the currently signin user

GET http://localhost:3000/auth/whoami

###Signout

POST http://localhost:3000/auth/signout


###find all users using a given email

GET http://localhost:3000/auth?email=asdf@asdf2.com

###Delete a users given id

DELETE http://localhost:3000/auth/6



###update a user

PATCH http://localhost:3000/auth/5
content-type: application/json

{
  "email": "aaaa@aaa.com"
}

### Set a color

# GET http://localhost:3000/auth/colors/hehe

# ### Get the color
# GET http://localhost:3000/auth/colors

