### find a particular user with given id
Get http://localhost:3000/auth/4

### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "unique@asdf2.com",
  "password": "asdlfkajsd"
}


###find all users using a given email

GET http://localhost:3000/auth/email=asdf@asdf.com

###Delete a users given id

DELETE http://localhost:3000/auth/6



###update a user

PATCH http://localhost:3000/auth/5
content-type: application/json

{
  "email": "aaaa@aaa.com"
}